apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications

resources:
  - nginx-deployment.yaml
#   - argocd/argocd-app.yaml
#   - argocd-resources/argocd-app.yaml
#   - ops-platform/argocd-app.yaml
#   - app-platform/argocd-app.yaml
